spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interactive_map?serverTimezone=Europe/Minsk&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: testtest
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-fauto: validate
  flyway:
    enabled: true
    ignoreMissingMigrations: true
    cleanOnValidationError: true
server:
#  address: 178.64.154.170
#  port: 8080
